# Generated by Django 6.0.2 on 2026-07-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('SHIPPING', 'Shipping'), ('RETURNS', 'Returns'), ('PAYMENT', 'Payment'), ('ACCOUNT', 'Account')], default='GENERAL', max_length=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='DeshiCart', max_length=180)),
                ('store_email', models.EmailField(blank=True, default='', max_length=254)),
                ('store_phone', models.CharField(blank=True, default='', max_length=32)),
                ('store_address', models.TextField(blank=True, default='')),
                ('currency', models.CharField(default='BDT', max_length=8)),
                ('currency_symbol', models.CharField(default='৳', max_length=8)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=180)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, default='', max_length=180)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('social_facebook', models.URLField(blank=True, default='')),
                ('social_instagram', models.URLField(blank=True, default='')),
                ('social_twitter', models.URLField(blank=True, default='')),
                ('social_youtube', models.URLField(blank=True, default='')),
                ('security_2fa_required', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
