# Generated by Django 6.0.2 on 2026-07-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('favicon_url', models.URLField(blank=True, default='', max_length=500)),
                ('primary_color', models.CharField(default='#EA580C', max_length=12)),
                ('accent_color', models.CharField(default='#FBBF24', max_length=12)),
                ('ink_color', models.CharField(default='#0F172A', max_length=12)),
                ('bg_color', models.CharField(default='#FFF7ED', max_length=12)),
                ('hero_title', models.CharField(default='Shop the deshi way', max_length=200)),
                ('hero_subtitle', models.CharField(default='Handpicked local products, delivered fast.', max_length=300)),
                ('hero_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('hero_cta_label', models.CharField(default='Shop now', max_length=60)),
                ('hero_cta_link', models.CharField(default='/products', max_length=255)),
                ('footer_text', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appearance',
                'verbose_name_plural': 'Appearance',
            },
        ),
    ]
