# Generated by Django 6.0.2 on 2026-06-30 11:33
#
# NOTE: Original migration was AlterField from UUIDField -> BigAutoField.
# Django auto-generates SQL USING "id"::bigint for that cast, which fails on
# PostgreSQL because uuid -> bigint is not implicitly coercible. We also need
# to convert order_orderitem.order_id from uuid to bigint, because the FK to
# order_order.id was created in 0001_initial with matching uuid types.
#
# Since the order tables are empty on a fresh Neon migration, we drop the FK
# constraint via a DO block, convert both columns via USING 0, and re-attach
# the FK constraint with matching bigint types. state_operations keeps Django
# model state in sync with the actual DB schema.
#
# Co-authored: 2026-07-08 Neon migration fixup.

from django.db import migrations, models

SQL = ["DO $$\nDECLARE r record;\nBEGIN\n  FOR r IN SELECT conname FROM pg_constraint\n             WHERE conrelid = (SELECT oid FROM pg_class WHERE relname = 'order_orderitem')\n               AND contype = 'f'\n               AND pg_get_constraintdef(oid) LIKE '%order_order%'\n  LOOP\n    EXECUTE format('ALTER TABLE order_orderitem DROP CONSTRAINT %I', r.conname);\n  END LOOP;\nEND\n$$;", 'CREATE SEQUENCE IF NOT EXISTS order_order_id_seq;', 'ALTER TABLE "order_order" ALTER COLUMN "id" DROP DEFAULT;', 'ALTER TABLE "order_order" ALTER COLUMN "id" TYPE bigint USING 0;', 'ALTER TABLE "order_order" ALTER COLUMN "id" SET DEFAULT nextval(\'order_order_id_seq\'::regclass);', 'ALTER SEQUENCE order_order_id_seq OWNED BY "order_order"."id";', 'ALTER TABLE "order_orderitem" ALTER COLUMN "order_id" TYPE bigint USING 0;', 'ALTER TABLE "order_orderitem" ADD CONSTRAINT order_orderitem_order_id_fkey FOREIGN KEY (order_id) REFERENCES "order_order"(id) ON DELETE CASCADE;']

REVERSE_SQL = ['ALTER TABLE "order_orderitem" DROP CONSTRAINT IF EXISTS order_orderitem_order_id_fkey;', 'ALTER TABLE "order_orderitem" ALTER COLUMN "order_id" TYPE uuid USING gen_random_uuid();', 'ALTER TABLE "order_order" ALTER COLUMN "id" DROP DEFAULT;', 'DROP SEQUENCE IF EXISTS order_order_id_seq;', 'ALTER TABLE "order_order" ALTER COLUMN "id" TYPE uuid USING gen_random_uuid();', 'ALTER TABLE "order_order" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();']

class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_cartitem_quantity_alter_order_user_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=SQL,
            reverse_sql=REVERSE_SQL,
            state_operations=[
                migrations.AlterField(
                    model_name='order',
                    name='id',
                    field=models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
        ),
    ]
