# Generated by Django 6.0.2 on 2026-07-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_address_order_notes_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NOT PAID', 'Not Paid'), ('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('READY TO SHIP', 'Ready to Ship'), ('TRANSIT', 'In Transit'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECT', 'Rejected'), ('REFUNDED', 'Refunded')], default='NOT PAID', max_length=20),
        ),
    ]
